accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login_check, name='login'),
    path('logout/', logout, name='logout'),
    path('follow/', follow, name='follow'),
]

insta_clone/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    # path('accounts/', include('allauth.urls')),

    path('post/', include('post.urls', namespace='post')),
    path('', lambda r: redirect('post:post_list'), name='root')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('new/', post_new, name='post_new'),
    path('edit/<int:pk>/', post_edit, name='post_edit'),
    path('delete/<int:pk>/', post_delete, name='post_delete'),
    path('like/', post_like, name='post_like'),
    path('bookmark/', post_bookmark, name='post_bookmark'),
    path('comment/new/', comment_new, name='comment_new'),
    path('comment/delete/', comment_delete, name='comment_delete'),
    path('explore/tags/<tag>/', post_list, name='post_search'),
    path('<int:pk>/', post_detail, name='post_detail'),
    path('comment_detail/new/', comment_new_detail, name='comment_new_detail'),
    path('<username>/list/detail/', my_post_list, name='my_post_list')
]

post/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

import re


def photo_path(instance, filename):
    from time import strftime
    from random import choice
    import string

    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ''.join(arr)
    extension = filename.split('.')[-1]
    return '{}/{}/{}.{}'.format(strftime('post/%y/%m/%d/'), instance.author.username, pid, extension)


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = ProcessedImageField(upload_to=photo_path,
                                processors=[ResizeToFill(600, 600)],
                                format='PNG',
                                options={'quality': 100})
    content = models.CharField(max_length=200, help_text="최대 200자 입력 가능")
    like_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                           blank=True,
                                           related_name='like_user_set',
                                           through='Like')
    bookmark_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                               blank=True,
                                               related_name='bookmark_user_set',
                                               through='Bookmark')
    tag_set = models.ManyToManyField('Tag', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    @property
    def like_count(self):
        return self.like_user_set.count()

    @property
    def bookmark_count(self):
        return self.bookmark_user_set.count()

    def tag_save(self):
        # 정규표현식 사용해 tag 저장
        tags = re.findall(r'#(\w+)\b', self.content)

        if not tags:
            return

        for t in tags:
            tag, tag_created = Tag.objects.get_or_create(name=t)
            self.tag_set.add(tag)  # ManyToManyField에 인스턴스 추가

    def __str__(self):
        return self.content


# 좋아요
class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (
            ('user', 'post')
        )


# 북마크
class Bookmark(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (
            ('user', 'post')
        )


# 댓글
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=40)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.content


# 태그
class Tag(models.Model):
    name = models.CharField(max_length=140, unique=True)

    def __str__(self):
        return self.name

post/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    photo = forms.ImageField(label='')
    content = forms.CharField(label='', widget=forms.Textarea(attrs={
        'class' : 'post-new-content',
        'rows' : 5,
        'cols' : 50,
        'placeholder' : '140자 까지 등록가능합니다.'
    }))

    class Meta:
        model = Post
        fields = ['photo', 'content']


class CommentForm(forms.ModelForm):
    content = forms.CharField(label='', widget=forms.TextInput(attrs={
        'class' : 'comment-form',
        'size': '70px',
        'placeholder' : '댓글 달기..',
        'maxlength' : '40'
    }))

    class Meta:
        model = Comment
        fields = ['content']

post/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .admin import PostForm
from .forms import CommentForm
from .models import Post, Like, Comment, Tag

import json
from django.views.decorators.http import require_POST
from django.http import HttpResponse

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from django.db.models import Count

'''
    1. 요청이 들어오면 posts 변수에 Post 전부를 저장
    2. 사용자가 로그인 상태일 때, 사용자 이름을 저장 -> 유저 모델 내용을 확인 
    3. 사용자 프로필 저장 -> HTML 렌더링 (유저프로필, 포스트 리스트)
'''


# Create your views here.
def post_list(request, tag=None):
    # Tag 검색에 따른 post_list 가져오기
    if tag:
        # 위에서 받은 태그를 대소문자 구분없이 tag_set_name로 검색한다.
        post_list = Post.objects.filter(tag_set__name__iexact=tag) \
            .prefetch_related('tag_set', 'like_user_set__profile', 'comment_set__author__profile',  # 1:1, 1:N, M:N 가능
                              'author__profile__follower_user', 'author__profile__follower_user__from_user') \
            .select_related('author__profile')  # 1:1의 관계에서만 사용
    else:
        post_list = Post.objects.all() \
            .prefetch_related('tag_set', 'like_user_set__profile', 'comment_set__author__profile',
                              'author__profile__follower_user', 'author__profile__follower_user__from_user') \
            .select_related('author__profile')

    comment_form = CommentForm()
    paginator = Paginator(post_list, 3)
    page_num = request.POST.get('page')

    try:
        posts = paginator.page(page_num)
    except PageNotAnInteger:
        # page 파라미터가 int가 아닌 값이 들어오면 1로 넘겨준다.
        posts = paginator.page(1)
    except EmptyPage:
        # page가 페이지를 넘어서면 마지막 페이지를 넘겨준다.
        posts = paginator.page(paginator.num_pages)

    # Ajax 호출 되었을 경우
    # if request.is_ajax():        <-- # django 4.x에서는 삭제됨.
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        return render(request, 'post/post_list_ajax.html', {
            'posts': posts,
            'comment_form': comment_form,
        })

    if request.method == 'POST':
        tag = request.POST.get('tag')
        tag_clean = ''.join(e for e in tag if e.isalnum())

        return redirect('post:post_search', tag_clean)

    if request.user.is_authenticated:
        username = request.user
        user = get_object_or_404(get_user_model(), username=username)
        user_profile = user.profile

        # following
        following_set = request.user.profile.get_following
        following_post_list = Post.objects.filter(author__profile__in=following_set)

        return render(request, 'post/post_list.html', {
            'user_profile': user_profile,
            'posts': posts,
            'comment_form': comment_form,
            'following_post_list': following_post_list
        })
    else:
        return render(request, 'post/post_list.html', {
            'posts': posts,
            'comment_form': comment_form
        })


# 신규 포스트 작성
@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            post.tag_save()
            messages.info(request, '새 글이 등록되었습니다.')

            return redirect('post:post_list')  # post/post_list 페이지로 이동
    else:
        form = PostForm()
    return render(request, 'post/post_new.html', {
        'form': form
    })


# 포스트 편집
@login_required
def post_edit(request, pk):
    # get_object_or_404 : 모델에서 찾는 요소가 있으면 반환, 없으면 404에러
    # objects.get을 사용 시, 찾는 요소가 없다면 500에러가 발생한다.
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user:
        messages.warning(request, '잘못된 접근입니다.')

        return redirect('post:post_list')

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            # post.tag_set.clear()
            # post.tag_save()
            messages.success(request, '수정 완료')

            return redirect('post:post_list')

    else:
        form = PostForm(instance=post)

    return render(request, 'post/post_edit.html', {
        'post': post,
        'form': form
    })


# 포스팅 삭제
@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if post.author != request.user or request.method != 'POST':
        messages.warning(request, '잘못된 접근입니다.')

    else:
        post.delete()
        messages.success(request, '삭제 완료')

    return redirect('post:post_list')


@login_required
@require_POST
def post_like(request):
    pk = request.POST.get('pk', None)
    post = get_object_or_404(Post, pk=pk)
    post_like, post_like_created = post.like_set.get_or_create(user=request.user)

    if not post_like_created:
        post_like.delete()
        message = "좋아요를 취소합니다."
    else:
        message = "좋아요"

    context = {'like_count': post.like_count, 'message': message}

    return HttpResponse(json.dumps(context), content_type="application/json")


@login_required
@require_POST
def post_bookmark(request):
    pk = request.POST.get('pk', None)
    post = get_object_or_404(Post, pk=pk)
    post_bookmark, post_bookmark_created = post.bookmark_set.get_or_create(user=request.user)

    if not post_bookmark_created:
        post_bookmark.delete()
        message = "북마크 취소"
    else:
        message = "북마크"

    context = {'bookmark_count': post.bookmark_count,
               'message': message}

    return HttpResponse(json.dumps(context), content_type="application/json")


'''
    comment(댓글)
    
'''


@login_required
def comment_new(request):
    pk = request.POST.get('pk')  # ajax를 통신하는 부분
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()

            return render(request, 'post/comment_new_ajax.html', {
                'comment': comment
            })

    return redirect('post:post_list')


# 상세페이지에서 댓글 추가 시 사용
@login_required
def comment_new_detail(request):
    pk = request.POST.get('pk')
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()

            return render(request, 'post/comment_new_detail_ajax.html', {
                'comment': comment
            })


@login_required
def comment_delete(request):
    pk = request.POST.get('pk')
    comment = get_object_or_404(Comment, pk=pk)
    if request.method == 'POST' and request.user == comment.author:
        comment.delete()
        message = '삭제완료'
        status = 1

    else:
        message = '잘못된 접근입니다'
        status = 0

    return HttpResponse(json.dumps({'message': message, 'status': status, }), content_type="application/json")


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comment_form = CommentForm()

    return render(request, 'post/post_detail.html', {
        'comment_form': comment_form,
        'post': post
    })


@login_required
def comment_new_detail(request):
    pk = request.POST.get('pk')
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()

            return render(request, 'post/comment_new_detail_ajax.html', {
                'comment': comment
            })


@login_required
def my_post_list(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    user_profile = user.profile
    target_user = get_user_model().objects.filter(id=user.id)\
                                  .select_related('profile')\
                                  .prefetch_related('profile__follower_user__from_user', 'profile__follow_user__to_user')

    post_list = user.post_set.all()
    all_post_list = Post.objects.all()

    return render(request, 'post/my_post_list.html', {
        'user_profile': user_profile,
        'target_user': target_user,
        'post_list' : post_list,
        'all_post_list' : all_post_list,
        'username' : username
    })

post/templates/post/comment_new_ajax.html
<div class="comment-detail" id="comment {{ comment.id }}">
    <div class="nick_name m_text"> {{ comment.author.profile.nickname }} </div>
    <div> {{ comment.content }} </div>
    {% if user == comment.author %}
    <input type="button" class="del-comment" data-name="comment_delete" value="삭제" name="{{ comment.id }}">
    {% endif %}
</div>

post/templates/post/comment_new_detail_ajax.html
<div class="user_container-detail" id="comment {{ comment.id }}">
    <div class="user"><img src="{{ comment.author.profile.picture.url }}" alt="user"></div>
    <div class="comment">
        <span class="user_id"> {{ comment.author.profile.nickname }}</span>
        <span> {{ comment.content }}</span>
        <span>
            {% if user == comment.author %}
            <input type="button" class="del-comment" data-name="comment_delete" value="삭제" name="{{ comment.id }}">
            {% endif %}
        </span>
        <div class="time">{{ comment.created_at|timesince }}</div>
    </div>
</div>

post/templates/post/my_post_list.html
{% extends "post/layout.html" %}
{% load static %}

{% block head %}

<link rel="stylesheet" href="{% static 'css/mylist.css' %}">
<link rel="stylesheet" href="{% static 'css/common.css' %}">
<link rel="stylesheet" href="{% static 'css/profile.css' %}">

{% endblock %}

{% block content %}
<div id="main_container">

        <section class="b_inner">

            <div class="hori_cont">
                <div class="profile_wrap">
                    <div class="profile_img">
                        {% if user_profile.picture %}
                        <img src="{{ user_profile.picture.url }}" alt="착한호랑이">
                        {% else %}
                        <img src="{% static 'imgs/img_section/img01.jpg' %}" alt="착한호랑이">
                        {% endif %}
                    </div>
                </div>

                <div class="detail">
                    <div class="top">
                        <div class="user_name">{{ user.profile.nickname }}</div>
                        <a href="{% url 'accounts:logout' %}" class="logout">로그아웃</a>
                    </div>

                    <ul class="middle">
                        <li>
                            <span>게시물</span>
                            {{ user.post_set.count }}
                        </li>
                        <li>
                            <span>팔로워</span>
                            {{ user.profile.follower_count }}
                        </li>
                        <li>
                            <span>팔로우</span>
                            {{ user.profile.following_count }}
                        </li>
                    </ul>
                    <p class="about">
                        <span class="nick_name on">내가쓴글</span>
                        <span class="book_mark">북마크</span>
                    </p>

                </div>
            </div>

            <div class="mylist_contents contents_container active">
                {% for post in post_list %}
                <div class="pic">
                    <a href="#"><img src="{{ post.photo.url }}" alt=""></a>
                </div>
                {% endfor %}
            </div>


            <div class="bookmark_contents contents_container">

                {% for post in all_post_list %}
                    {% for bookmark_user in post.bookmark_user_set.all %}
                    <div class="pic">
                        {% if user == bookmark_user.profile.user %}
                            <a href="#"><img src="{{ post.photo.url }}" alt=""></a>
                        {% endif%}
                    </div>
                    {% endfor %}
                {% endfor%}
            </div>

        </section>
    </div>


{% endblock %}

{% block js %}
<script src="{% static 'js/profile.js' %}"></script>
{% endblock %}

post/templates/post/script_ajax.html
<script type="text/javascript">
( function(){

    const delegation = document.querySelector('.contents_box');
    const side_box = document.querySelector('.side_box');
    const header = document.querySelector('#header');

    function resizeFunc() {
        console.log('리사이즈');
        if (scrollY >= 10) {
            let calcWidth = (window.innerWidth * 0.5) + 167;
            if (side_box) {
                side_box.style.left = calcWidth + "px";
            }
        }
    }

    function scrollFunc() {
        let scrollHeight = scrollY + window.innerHeight;
        const documentHeight = document.body.scrollHeight;

        if (scrollY >= 10) {
            header.classList.add('on');
            resizeFunc();
            if (side_box) {
                side_box.classList.add('on');
            }
        } else {
            header.classList.remove('on');
            if (side_box) {
                side_box.classList.remove('on');
                side_box.removeAttribute('style');
            }
        }

        if (scrollHeight >= documentHeight) {
            const page = document.querySelector('#page').value;
            const end_page = {{ posts.paginator.num_pages }}

            if (page > end_page) {
                return;
            }

            document.querySelector('#page').value = parseInt(page) + 1;
            callMorePostAjax(page);
        }
    }

    function callMorePostAjax(page) {
        const end_page = {{ posts.paginator.num_pages }};

        if (page > end_page) {
            return;
        }

        $.ajax({
            type: 'POST',
            url: "{% url 'post:post_list' %}",
            data: {
                'page':page,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            dataType: 'html',
            success: addMorePostAjax,
            error: function(request, status, error) {
                alert("code : " + request.status + "\n" + "message:" + request.responseText + "\n" + "error:" + error);
            }
        });
    }

    function addMorePostAjax(data, textStatus, jqXHR) {
        let post = document.querySelector('#post_list_ajax');
        post.insertAdjacentHTML('beforeend', data);
    }

    function delegationFunc(e) {
        let elem = e.target;

        console.log(elem);

        while (!elem.getAttribute('data-name')){
            elem = elem.parentNode;

            if (elem.nodeName === 'BODY'){
                elem = null;
                return;
            }
        }

        if (elem.matches('[data-name="heartbeat"]')){
            console.log('하트!');

            var pk = elem.getAttribute('name');
            console.log(pk);

            $.ajax({
                type: "POST",
                url: "{% url 'post:post_like' %}",
                data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                dataType: "json",
                success: function (response){
                    // alert('성공!');
                    var likeCount = document.querySelector('#like-count-'+pk);
                    likeCount.innerHTML = '좋아요' + response.like_count + '개';
                },
                error: function (request, status, error) {
                    alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                },
            });

        }else if (elem.matches('[data-name="bookmark"]')){
            console.log('북마크!');

            var pk = elem.getAttribute('name');
            console.log(pk);

            $.ajax({
                type: "POST",
                url: "{% url 'post:post_bookmark' %}",
                data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                dataType: "json",
                success: function (response){
                    // alert('성공!');
                    var bookmarkCount = document.querySelector('#bookmark-count-'+pk);
                    bookmarkCount.innerHTML = '북마크' + response.bookmark_count + '개';
                },
                error: function (request, status, error) {
                    alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                },
            });

        } else if (elem.matches('[data-name="comment"]')){

            console.log('새댓글')
            var pk = elem.getAttribute('name');
            var content = document.querySelector('#add-comment-post'+pk+'>input[type=text]').value;
            console.log(content);

            if(content.length > 140) {
                alert("댓글은 최대 140자 입력 가능합니다. 현재 글자수 :"+content.length);
                return;
            }

            if(content.length == 0) {
                alert("글자를 하나라도 넣어주세요. 현재 글자수 :"+content.length);
                return;
            }

            $.ajax({
                type: "POST",
                url: "{% url 'post:comment_new' %}",
                data: {
                    'pk': pk,
                    'content': content,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                dataType: "html",
                success: function(data, textStatus, jqXHR){
                    console.log("성공!")
                    document.querySelector("#comment-list-ajax-post"+pk).insertAdjacentHTML("afterbegin", data);

                },
                error: function(request, status, error){
                    alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                },
            });

        } else if(elem.matches('[data-name="comment_delete"]')){
            var pk = elem.getAttribute('name');

            $.ajax({
                type: "POST",
                url: "{% url 'post:comment_delete' %}",
                data: {
                    'pk': pk,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                dataType: "json",
                success: function(response){
                    if(response.status){
                        document.querySelector('#comment'+pk).remove();
                    }
                },
                error: function(request, status, error){
                    alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                }
            });

        } else if(elem.matches('[data-name="follow"]')){
            console.log("팔로우!");
            var pk = elem.getAttribute('name');

            $.ajax({
                type:"POST",
                url: "{% url 'accounts:follow' %}",
                data: {
                    'pk': pk,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                dataType: "json",
                success: function(response){
                    console.log("성공");
                    if(response.status){
                        document.querySelector('input.follow[name=\''+pk+'\']').value="팔로잉";
                    }else{
                        document.querySelector('input.follow[name=\''+pk+'\']').value="팔로우";
                    }
                },
                error: function(request, status, error){
                    alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                }
            })
        }
        elem.classList.toggle('on');
    }

    // 뷰의 크기가 변할 때, resizeFunc 실행
    window.addEventListener('resize', resizeFunc);
    // 스크롤이 이동했을 때, scrollFunc 실행
    window.addEventListener('scroll', scrollFunc);
    delegation.addEventListener('click', delegationFunc);

})();

</script>

post/templates/post/script_ajax_detail.html
<script type="text/javascript">
(function(){

    const delegation = document.querySelector('.contents_box')

    function delegationFunc(e) {
        let elem = e.target;

        while (!elem.getAttribute('data-name')){
            elem = elem.parentNode;

            if (elem.nodeName === 'BODY'){
                elem = null;
                return;
            }
        }

        if (elem.matches('[data-name="follow"]')){
            console.log('팔로우');

            var pk = elem.getAttribute('name')

            $.ajax({
                type: "POST",
                url: "{% url 'accounts:follow' %}",
                data: {
                    'pk': pk,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                dataType: "json",
                success: function(response){
                    // alert('성공!')
                    if(response.status){
                        document.querySelector('input.follow[name=\''+pk+'\']').value="팔로잉";
                    }else{
                        document.querySelector('input.follow[name=\''+pk+'\']').value="팔로우";
                    }


                },
                error: function(request, status, error){
                    alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                },
                })
            }else if (elem.matches('[data-name="heartbeat"]')){
                    var pk = elem.getAttribute('name')

                     $.ajax({
                        type: "POST",
                        url: "{% url 'post:post_like' %}",
                        data: {
                            'pk': pk,
                            'csrfmiddlewaretoken': '{{ csrf_token }}',
                        },
                        dataType: "json",
                        success: function(response){
                        // alert('성공!')
                            var likeCount = document.querySelector('#like-count-'+pk);
                            likeCount.innerHTML = '좋아요' + response.like_count + '개';
                        },
                        error: function(request, status, error){
                            alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                        },
                    })
            } else if (elem.matches('[data-name="bookmark"]')){
                    var pk = elem.getAttribute('name')

                    $.ajax({
                            type: "POST",
                            url: "{% url 'post:post_bookmark' %}",
                            data: {
                                'pk': pk,
                                'csrfmiddlewaretoken': '{{ csrf_token }}',
                            },
                            dataType: "json",
                            success: function (response){
                                // alert('성공!');
                                var bookmarkCount = document.querySelector('#bookmark-count-'+pk);
                                bookmarkCount.innerHTML = '북마크' + response.bookmark_count + '개';
                            },
                            error: function(request, status, error){
                                alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                            },
                        })
            }else if (elem.matches('[data-name="comment"]')){
                var pk = elem.getAttribute('name');
                var content = document.querySelector('#add-comment-post'+pk+'>input[type=text]').value;

                if(content.length > 140) {
                    alert("댓글은 최대 140자 입력 가능합니다. 현재 글자수 :"+content.length);
                }

                if(content.length == 0) {
                    alert("한글자 이상 입력해 주세요. 현재 글자수 :"+content.length);
                }

                $.ajax({
                    type: "POST",
                    url: "{% url 'post:comment_new_detail' %}",
                    data: {
                        'pk':pk,
                        'content': content,
                        'csrfmiddlewaretoken': '{{ csrf_token}}',
                    },
                    dataType: "html",
                    success: function(data, textStatus, jqXHR){
                        document.querySelector("#comment-list-ajax-post"+pk).insertAdjacentHTML("afterbegin", data);
                    },
                    error: function(reqeust, status, error){
                        alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                    },
                });
            }else if(elem.matches('[data-name="comment_delete"]')){
                var pk = elem.getAttribute('name');

                $.ajax({
                    type: "POST",
                    url: "{% url 'post:comment_delete' %}",
                    data: {
                        'pk': pk,
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                    },
                    dataType: "json",
                    success: function(response){
                        if(response.status){
                            document.querySelector('#comment'+pk).remove();
                        }

                    },
                    error: function(reqeust, status, error){
                        alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                    },
                })
            }
        elem.classList.toggle('on');
    }

    delegation.addEventListener('click', delegationFunc);
})();
</script>